---

- name: Copy zfs-auto-snapshot script
  copy:
    mode: 0775
    src: zfs-auto-snapshot.sh
    dest: "{{ zfs_auto_snapshot_path }}/zfs-auto-snapshot"

- name: Create /usr/local/share/man/man8/ directory
  file:
    path: /usr/local/share/man/man8/
    state: directory

- name: Copy zfs-auto-snapshot man
  copy:
    src: zfs-auto-snapshot.8
    dest: /usr/local/share/man/man8/zfs-auto-snapshot.8

- name: Add cron
  template:
    src: cron.j2
    dest: /etc/cron.d/zfs-auto-snapshot
